#!/bin/sh
#
# you should run this as source, root user
#

# we're just installing the default dev tools package group
yum -y groupinstall "Development Tools"
# git
yum -y install git
# screen!
yum -y install screen