#!/bin/sh
#
# you should run this as source; assuming you're running this as root
#

# vars
JAVA_BASE_URL=http://resources.ohnosequences.com/bin/jdk/x64/latest/jdk.bin
JAVA_BIN_FILE=jdk.bin
JAVA_INSTALL_BASE=/opt
JAVA_INSTALL_FOLDER=java
JAVA_INSTALL_PATH=$JAVA_INSTALL_BASE/$JAVA_INSTALL_FOLDER


# create folder and go into
cd $JAVA_INSTALL_BASE
mkdir -p $JAVA_INSTALL_FOLDER
cd $JAVA_INSTALL_FOLDER

# download jdk, make it exec
wget -O $JAVA_BIN_FILE $JAVA_BASE_URL
chmod u+x $JAVA_BIN_FILE

# automated install trick
echo "\n" | ./$JAVA_BIN_FILE 1>/dev/null

# clean stuff
rm $JAVA_BIN_FILE

# get the folder and set JAVA_INSTALL_PATH
JAVA_INSTALL_PATH=$JAVA_INSTALL_PATH/`ls | grep jdk1*`
EXPORT_JAVA_HOME_STRING="export JAVA_HOME="$JAVA_INSTALL_PATH
EXPORT_JAVA_TO_PATH_STRING="export PATH=\$JAVA_HOME/bin:\$PATH"

# make JAVA_HOME globally available; This should be in terms of JAVA_INSTAL_PATH
echo "JAVA_HOME="$JAVA_INSTALL_PATH | tee -a /etc/environment
echo "PATH=\$JAVA_HOME/bin:\$PATH" | tee -a /etc/environment
source /etc/environment

# root $JAVA_HOME conf; don't know how sensible is this
echo "JAVA_HOME="$JAVA_INSTALL_PATH | tee -a /root/.bash_profile
echo "PATH=\$JAVA_HOME/bin:\$PATH" | tee -a /root/.bash_profile
echo $EXPORT_JAVA_HOME_STRING | tee -a /root/.bash_profile
echo $EXPORT_JAVA_TO_PATH_STRING | tee -a /root/.bash_profile
#source it!
source /root/.bash_profile

# ec2-user $JAVA_HOME conf
echo "JAVA_HOME="$JAVA_INSTALL_PATH | tee -a /home/ec2-user/.bash_profile
echo "PATH=\$JAVA_HOME/bin:\$PATH" | tee -a /home/ec2-user/.bash_profile
echo $EXPORT_JAVA_HOME_STRING | tee -a /home/ec2-user/.bash_profile
echo $EXPORT_JAVA_TO_PATH_STRING | tee -a /home/ec2-user/.bash_profile
# source it!
source /home/ec2-user/.bash_profile

# sanity check:
java -version