#!/bin/sh
#
# you should run this as source, root user
#
base_url=http://resources.ohnosequences.com

# create folder
mkdir -p /opt/matrix2png
cd /opt/matrix2png

# get file etc
wget $base_url/matrix2png/latest/matrix2png.tar.gz
tar -xzf matrix2png.tar.gz
cd matrix2png* 

# install deps
yum install gd gd-devel

# build and install
./configure
make
make install