#!/bin/sh
#
# you should run this as source, root user
# 

# vars
MUMMER_BASE_URL=http://resources.ohnosequences.com/bin/mummer/src/latest/mummer.tar.gz
MUMMER_INSTALL_BASE=/opt
MUMMER_SRC_FILE=mummer.tar.gz
MUMMER_INSTALL_FOLDER=mummer
MUMMER_INSTALL_PATH=$MUMMER_INSTALL_BASE/$MUMMER_INSTALL_FOLDER

# create folder and go into
cd $MUMMER_INSTALL_BASE
mkdir -p $MUMMER_INSTALL_FOLDER
cd $MUMMER_INSTALL_FOLDER

# download src tarball, extract
wget -O $MUMMER_SRC_FILE $MUMMER_BASE_URL
tar -xzf $MUMMER_SRC_FILE

# install! #

# get path
MUMMER_BIN_PATH=${MUMMER_INSTALL_PATH}/`ls | grep MUM*`
ADD_MUMMER_TO_PATH_STRING="PATH=${MUMMER_BIN_PATH}:\$PATH"

cd $MUMMER_BIN_PATH
# log the output of make check
make check > check.log
# build
make install
# add MUMmer to path
echo "${ADD_MUMMER_TO_PATH_STRING}" | tee -a /etc/environment
echo "${ADD_MUMMER_TO_PATH_STRING}" | tee -a /home/ec2-user/.bash_profile
