#!/bin/sh
#
# you should run this as source, root user
#
base_url=http://resources.ohnosequences.com

# create folder
mkdir -p /opt/solexaQA
cd /opt/solexaQA

# get file
wget $base_url/solexaQA/latest/solexaQA.tar.gz
tar -xzf solexaQA.tar.gz
rm solexaQA.tar.gz
chmod 755 ./*

cp -p ./* /usr/bin/
cp -p ./DynamicTrim.pl /usr/bin/dynamictrim
cp -p ./LengthSort.pl /usr/bin/lengthsort
cp -p ./SolexaQA.pl /usr/bin/solexaqa